'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/shared/Navbar";

import Menu from "@/components/shared/Menu";
import Providers from "./providers";
import { useAuth } from "@/providers/AuthProvider";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({ children }) {

  // const pathname = usePathname()

//   const router = useRouter()
// const {user} = useAuth();
// if(!user && !pathname.includes('/login' )  ){
//   return router.push('/login')
// }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


  

<Providers>
<div className=" min-h-[100vh] bg-[#0C0A2B] rounded-xl shadow-md mx-auto">
  <Navbar/>
<Menu />

{children}
</div>
</Providers>









     
      </body>
    </html>
  );
}