
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/providers/TanStackProvider";
import Navbar from "@/components/shared/Navbar";
import { AuthProvider } from "@/providers/AuthProvider";
import Menu from "@/components/shared/Menu";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<AuthProvider>
  
<TanStackProvider>
<div className=" min-h-[100vh] bg-[#0C0A2B] rounded-xl shadow-md mx-auto">
  <Navbar/>
<Menu />

{children}
</div>

</TanStackProvider>
</AuthProvider>






     
      </body>
    </html>
  );
}
